### ISSUE TITLE
Create site skeleton with routing & set up empty pages

### ISSUE THREAD

**Issue by aflashyrhetoric** [adelieco/adg-community-site#1]
We can start with this and then divide up the work. I'll be working on the design in the meantime, please let me know if you have any questions or ideas :bowing_man: thank you!

**Comment by CodeKommissar** [comment]
Here is the first version of the skeleton of the site: https://github.com/adelieco/adg-community-site/tree/skeleton-site

**Comment by aflashyrhetoric** [comment]
Great! Closing this issue!
